%% BATCH_FACE_DETECTION
% 批量处理人脸检测
% 自动处理所有符合条件的图片

clear; close all; clc;

%% 图片列表
image_paths = {
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ih3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ih4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ih5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ih6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ih7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ih8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ihd65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10il3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10il4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10il5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10il6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10il7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10il8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10ild65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10im3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10im4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10im5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10im6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10im7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10im8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\f10i\\f10imd65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ih3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ih4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ih5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ih6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ih7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ih8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ihd65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09il3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09il4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09il5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09il6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09il7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09il8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09ild65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09im3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09im4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09im5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09im6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09im7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09im8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m09i\\m09imd65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ih3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ih4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ih5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ih6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ih7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ih8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ihd65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10il3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10il4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10il5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10il6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10il7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10il8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10ild65_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10im3k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10im4k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10im5k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10im6k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10im7k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10im8k_01.jpg'; ...
    'D:\\work\\secondYearMaster\\thesis\\reference\\appeal\\algorithms\\preference_evaluate\\deepskin\\data\\toMax\\rendered_2max\\m10i\\m10imd65_01.jpg'; ...
};

fprintf('总共需要处理 %d 张图片\n', length(image_paths));

%% 初始化检测统计
detection_stats.default_detected = 0;
detection_stats.lbp_detected = 0;
detection_stats.cart_detected = 0;

%% 创建结果目录
result_dir = fullfile(fileparts(mfilename('fullpath')), 'face_detection_results');
if ~exist(result_dir, 'dir')
    mkdir(result_dir);
end

%% 处理每张图片
results = cell(length(image_paths), 1);

for idx = 1:length(image_paths)
    img_path = image_paths{idx};
    fprintf('[%d/%d] 处理: %s\n', idx, length(image_paths), img_path);
    
    try
        % 读取图片
        img = imread(img_path);
        [h, w, ~] = size(img);
        
        % 初始化检测器
        faceMinSize = [80 80];
        
        % 1) 默认检测器
        faceDetector = vision.CascadeObjectDetector();
        faceDetector.MinSize = faceMinSize;
        bboxes1 = faceDetector(img);
        
        % 2) LBP检测器
        faceDetectorLBP = vision.CascadeObjectDetector('FrontalFaceLBP');
        faceDetectorLBP.MinSize = faceMinSize;
        bboxes2 = faceDetectorLBP(img);
        
        % 3) CART检测器
        faceDetectorCART = vision.CascadeObjectDetector('FrontalFaceCART');
        faceDetectorCART.MinSize = faceMinSize;
        bboxes3 = faceDetectorCART(img);
        
        % 创建可视化结果
        fig = figure('Visible', 'off');
        imshow(img); hold on;
        
        % 绘制检测框
        if ~isempty(bboxes1)
            for i = 1:size(bboxes1,1)
                rectangle('Position', bboxes1(i,:), 'EdgeColor', 'r', 'LineWidth', 2);
            end
        end
        
        if ~isempty(bboxes2)
            for i = 1:size(bboxes2,1)
                rectangle('Position', bboxes2(i,:), 'EdgeColor', 'g', 'LineWidth', 2);
            end
        end
        
        if ~isempty(bboxes3)
            for i = 1:size(bboxes3,1)
                rectangle('Position', bboxes3(i,:), 'EdgeColor', 'b', 'LineWidth', 2);
            end
        end
        
        % 添加图例
        legend({'Cascade (Default)', 'LBP', 'CART'}, 'Location', 'bestoutside');
        
        % 提取文件名信息
        [path_str, name, ~] = fileparts(img_path);
        
        % 保存结果图
        out_filename = [name '_detection_test.jpg'];
        out_path = fullfile(result_dir, out_filename);
        imwrite(getframe(fig).cdata, out_path);
        
        close(fig);
        
        % 保存检测结果
        result = struct();
        result.img_path = img_path;
        result.img_size = [w, h];
        result.bboxes_default = bboxes1;
        result.bboxes_lbp = bboxes2;
        result.bboxes_cart = bboxes3;
        result.output_path = out_path;
        
        % 计算检测统计
        result.detected_default = ~isempty(bboxes1);
        result.detected_lbp = ~isempty(bboxes2);
        result.detected_cart = ~isempty(bboxes3);
        result.num_faces_default = size(bboxes1, 1);
        result.num_faces_lbp = size(bboxes2, 1);
        result.num_faces_cart = size(bboxes3, 1);
        
        results{idx} = result;
        
        % 更新全局统计
        if result.detected_default
            detection_stats.default_detected = detection_stats.default_detected + 1;
        end
        if result.detected_lbp
            detection_stats.lbp_detected = detection_stats.lbp_detected + 1;
        end
        if result.detected_cart
            detection_stats.cart_detected = detection_stats.cart_detected + 1;
        end
        
        fprintf('  完成: 默认=%d, LBP=%d, CART=%d\n', ...
                result.num_faces_default, result.num_faces_lbp, result.num_faces_cart);
        
    catch ME
        fprintf('  错误: %s\n', ME.message);
        results{idx} = struct('img_path', img_path, 'error', ME.message);
    end
end

%% 保存汇总结果
summary_file = fullfile(result_dir, 'detection_summary.mat');
save(summary_file, 'results', 'detection_stats');

% 生成报告
report_file = fullfile(result_dir, 'detection_report.txt');
fid = fopen(report_file, 'w');
fprintf(fid, '人脸检测结果报告\n');
fprintf(fid, '生成时间: %s\n', datestr(now));
fprintf(fid, '图片总数: %d\n', length(image_paths));
fprintf(fid, '\n检测统计:\n');
fprintf(fid, '默认检测器检测到人脸的图片数: %d\n', detection_stats.default_detected);
fprintf(fid, 'LBP检测器检测到人脸的图片数: %d\n', detection_stats.lbp_detected);
fprintf(fid, 'CART检测器检测到人脸的图片数: %d\n', detection_stats.cart_detected);
fclose(fid);

fprintf('\n处理完成！\n');
fprintf('结果保存在: %s\n', result_dir);
fprintf('汇总文件: %s\n', summary_file);
fprintf('报告文件: %s\n', report_file);
