name: CLIPIQA_AF_deepskin
model_type: GeneralIQAModel
num_gpu: 1
manual_seed: 42

datasets:
  train:
    name: deepskin_AF
    type: GeneralNRDataset
    dataroot_target: /root/autodl-tmp/rendered_2max
    meta_info_file: /root/autodl-tmp/iqa_pytorch_train/datasets/deepskin/global/AF/meta_info.csv
    split_index: split_name
    augment:
      resize: [256, 256]
      random_crop: 224
      hflip: true
    phase: train
    batch_size_per_gpu: 8
    num_worker_per_gpu: 4
  val:
    name: deepskin_AF
    type: GeneralNRDataset
    dataroot_target: /root/autodl-tmp/rendered_2max
    meta_info_file: /root/autodl-tmp/iqa_pytorch_train/datasets/deepskin/global/AF/meta_info.csv
    split_index: split_name
    phase: val

network:
  type: CLIPIQA

path:
  root: ./experiments
  pretrain_network: null
  strict_load_g: true
  param_key_g: params

train:
  optim:
    type: AdamW
    lr: !!float 1e-5
    weight_decay: !!float 1e-4
  scheduler:
    type: CosineAnnealingLR
    T_max: 3000
    eta_min: !!float 1e-7
  total_iter: 3000
  warmup_iter: -1
  mos_loss_opt:
    type: L1Loss
    loss_weight: 1.0

val:
  val_freq: 200
  save_checkpoint_freq: 500
  key_metric: srcc
  save_img: false
  metrics:
    srcc:
      type: calculate_srcc
    plcc:
      type: calculate_plcc

logger:
  print_freq: 50
  save_latest_freq: 500
  save_checkpoint_freq: 500
  use_tb_logger: true
