classdef (Hidden) AbstractGlobalSolver
%AbstractGlobalSolver A global optimization solver class. 
%   AbstractGlobalSolver is an abstract class representing a global
%   optimization solver. You cannot create instances of this class directly.  
%   You must create a derived class such as MultiStart or GlobalSearch,
%   by calling the class constructor.
%
%   All solvers that inherit from AbstractGlobalSolver have the following
%   properties and method:
%
%   AbstractGlobalSolver properties:
%       Display          - content level of display
%       TolFun           - minimum distance between two separate objective
%                          function values
%       TolX             - minimum distance between two separate points 
%       MaxTime          - time allowed to run the solver
%       StartPointsToRun - identify start points for the local solver 
%       OutputFcns       - user-defined output functions
%       PlotFcns         - functions to plot solver progress
%
%   AbstractGlobalSolver method:
%       run             - attempts to search for the best solution of a given
%                         optimization problem
%
%   See also MULTISTART, GLOBALSEARCH

%   Copyright 2009-2010 The MathWorks, Inc.
%   $Revision: 1.1.6.5 $  $Date: 2010/05/10 17:16:38 $
    
    properties
%DISPLAY Content level of display
%   The Display property is a string that defines the detail the global
%   solver will display about the solution process during and after its
%   run.
%
%   Display can take the following values:
%
%   'off'   : No display generated by the global solver
%   'final' : Generate display when the solver terminates
%   'iter'  : Display information as the solver progresses
%
%   See also MULTISTART, GLOBALSEARCH
        Display = 'final';
        
%TOLFUN Minimum distance between two separate objective function values 
%   The TolFun property sets the value of the tolerance that defines the 
%   separation of the objective function value. Two objective function 
%   values will be considered distinct if their distance is larger than 
%   TolFun.
%
%   See also MULTISTART, GLOBALSEARCH
        TolFun = 1e-6;
        
%TOLX Minimum distance between two separate points 
%   The TolX property sets the value of the tolerance that defines the 
%   separation of optimization variables. Two optimization variables (points)
%   will be considered distinct if their distance is larger than TolX.
%
%   See also MULTISTART, GLOBALSEARCH       
        TolX = 1e-6;

%MAXTIME Time allowed to run the solver
%   The MaxTime property sets the maximum total clock time (in seconds) the
%   solver will run. The solver will exit as soon as this time is reached
%   regardless of how many solutions (if any) were found.
%
%   See also MULTISTART, GLOBALSEARCH        
        MaxTime = Inf;        

%STARTPOINTSTORUN Identify start points for the local solver 
%   The StartPointsToRun property identifies which start points will be run
%   by the local solver during the main phase of the search. These can be 
%   either all of the start points ('all'), those feasible with respect to
%   the bounds ('bounds') or those feasible with respect to both bounds and
%   inequality constraints ('bounds-ineqs').
% 
%   See also MULTISTART, GLOBALSEARCH
    StartPointsToRun = 'all';
    
%OUTPUTFCNS User-defined output functions
%   The OutputFcns property assigns a function handle or a cell array of
%   function handles for user-defined output functions. With output
%   functions the user can stop the solver, or access (read-only) global
%   solver algorithm data after each local solver call. By default this
%   property is empty. The syntax of an output function is
%
%         stop = anOutputFcn(optimValues,state).
%
%   For more details see the Options Reference section in the Global
%   Optimization Toolbox User Guide.
% 
%   See also MULTISTART, GLOBALSEARCH
    OutputFcns = [];
    
%PLOTFCNS Functions to plot solver progress
%   The PlotFcns property assigns a function handle or a cell array of
%   function handles for functions that plot various measures of progress
%   while the global solver algorithm executes. By default this property is
%   empty. The syntax of a plot function is 
%
%         stop = aPlotFcn(optimValues,state).
%
%   For more details see the Options Reference section in the Global
%   Optimization Toolbox User Guide.
% 
%   See also MULTISTART, GLOBALSEARCH
    PlotFcns = [];    
    
    end
    
    properties(Access = protected)
        % Protected property to keep track of the version for the objects
        Version
    end
    
    methods (Abstract)
        [x,fval,exitflag,output,solutionSet] = run(obj,problem,startPointSets)
    end
    methods
        % Constructor
        function obj = AbstractGlobalSolver(varargin)
            firstInputObj = false;
           % Constructor without any arguments will create a solver with
           % default properties
           % First argument can be a GlobalSearch object, a MultiStart
           % object or parameter of a parameter-value pair            
            if nargin > 0
                if isa(varargin{1},'AbstractGlobalSolver')
                    if strcmp(class(varargin{1}),class(obj))
                        obj = varargin{1};
                    else
                        obj.Display = varargin{1}.Display;
                        obj.TolFun = varargin{1}.TolFun;
                        obj.TolX = varargin{1}.TolX;
                        obj.MaxTime = varargin{1}.MaxTime;
                        obj.StartPointsToRun = varargin{1}.StartPointsToRun;
                        obj.OutputFcns = varargin{1}.OutputFcns;
                        obj.PlotFcns = varargin{1}.PlotFcns;                        
                    end
                    firstInputObj = true;
                end
                if nargin > 1 && firstInputObj
                    agsProp = varargin(2:end);
                elseif nargin == 1 && ~firstInputObj
                    errid = 'globaloptim:AbstractGlobalSolver:invalidInput';
                    errmsg = 'A single input can be a MultiStart or GlobalSearch solver.';
                    error(errid,errmsg);
                else
                    agsProp = varargin;
                end
                if (nargin > 1) && (mod(length(agsProp),2) ~= 0)
                    error('globaloptim:AbstractGlobalSolver:notAPair', ...
                        'Arguments must occur in name-value pairs.');
                end
                while length(agsProp) >= 2
                    prop = agsProp{1};
                    if ~ischar(prop)
                        error('globaloptim:AbstractGlobalSolver:propertyNameNotString', ...
                            'Property name should be a string.');
                    end                    
                    val = agsProp{2};
                    agsProp = agsProp(3:end);                        
                    PName = i_isPublicExact(obj, prop, 'set');
                    if ~isempty(PName)
                        obj.(PName) = val;
                    else
                        % No match at all
                        className = class(obj);
                        error('globaloptim:AbstractGlobalSolver:invalidPropertyName', ...
                            'No public property %s exists for %s.', ...
                            prop, className);
                    end
                end
            end
        end
        function obj = set.Display(obj,value)
            % error check for Display property
            error(typeValueChecker('displayType',value));
            obj.Display = value;
        end
        function obj = set.TolFun(obj,value)
            % error check for TolFun property
            error(typeValueChecker('nonNegReal',value,'TolFun'));
            obj.TolFun = value;
        end
        function obj = set.TolX(obj,value)
            % error check for TolX property
            error(typeValueChecker('nonNegReal',value,'TolX'));
            obj.TolX = value;
        end
        function obj = set.MaxTime(obj,value)
            % error check for MaxTime property
            error(typeValueChecker('nonNegReal',value,'MaxTime'));
            obj.MaxTime = value;
        end
        function obj = set.StartPointsToRun(obj,value)
            % error check for StartPointsToRun property
            error(typeValueChecker('stringsType',value,...
                'StartPointsToRun',{'all','bounds','bounds-ineqs'}));
            obj.StartPointsToRun = value;
        end
        function obj = set.OutputFcns(obj,value)
            % error check for OutputFcns property
            error(typeValueChecker('functionOrCellArray',value,'OutputFcns'));
            obj.OutputFcns = value;
        end
        function obj = set.PlotFcns(obj,value)
            % error check for PlotFcns property
            error(typeValueChecker('functionOrCellArray',value,'PlotFcns'));
            obj.PlotFcns = value;
        end        
    end
    
    methods (Access = protected, Static)
        function msgstruct = checkProblem(problem, requiredFields, validValues)

            % Initialize error message string
            errmsg = '';

            % Perform checks on problem structure. First check whether
            % problem is a structure.
            if isstruct(problem) && isscalar(problem)
                % Check whether problem is a valid optim structure and
                % uses one of the valid solvers
                [validProblemStruct,validOptimProblemErrmsg] = ...
                    validOptimProblemStruct(problem,requiredFields,validValues);
                if validProblemStruct
                    % Check whether problem has an x0 field
                    if isempty(problem.x0)
                        errid = 'globaloptim:AbstractGlobalSolver:run:MissingX0';
                        errmsg = 'PROBLEM structure should have a non-empty X0 field.';
                    end
                else
                    errid = 'globaloptim:AbstractGlobalSolver:run:InvalidStructInput';
                    errmsg = sprintf('Invalid problem structure: %s',validOptimProblemErrmsg);
                end
            else
                errid = 'globaloptim:AbstractGlobalSolver:run:ProblemNotAStruct';
                errmsg = 'PROBLEM should be a scalar structure.';
            end
            
            % Create a error message structure
            msgstruct = struct('message', [], 'identifier', []);
            if isempty(errmsg)
                % Need to pass an empty message structure to error to make
                % it return without erroring
                msgstruct(1) = [];
            else
                msgstruct.message = errmsg;
                msgstruct.identifier = errid;
            end            
        end
    end
end % classdef

function CorrectIdent = i_isPublicExact(obj, Ident, Type)
% Check whether an identifier matches exactly to a public property or
% method.

publicIdents = i_getPublic(obj,Type);
CorrectIdent = '';
if strmatch(Ident,publicIdents,'exact');
    CorrectIdent = Ident;
end
end

function Names = i_getPublic(obj, Type)
% Return the list of public names for the specified type of operation.
% Type may be one of 'get', 'set' or 'call'.

% The list of public identifiers will depend on the exact class of the
% object, so a list is held for each unique class.

persistent PublicIdents
if isempty(PublicIdents)
    % Initialize the database of lists-per-class to be empty
    PublicIdents = struct;
end

Cname = class(obj);
if ~isfield(PublicIdents, Cname)
    % Initialize the lists of public identifiers for this class
    C = metaclass(obj);
    P = [C.Properties{:}];
    PropGet = strcmp({P.GetAccess}, 'public');
    PropSet = strcmp({P.SetAccess}, 'public');
    PropNames = {P.Name};

    M = [C.Methods{:}];
    MethAccess = strcmp({M.Access}, 'public');
    MethNames = {M.Name};

    PublicIdents.(Cname).get = PropNames(PropGet);
    PublicIdents.(Cname).set = PropNames(PropSet);
    PublicIdents.(Cname).call = MethNames(MethAccess);
end

Names = PublicIdents.(Cname).(Type);
end